### ISSUE TITLE
Regression Test multiple_upstreams nerver complete in PG13 beta3 builder with pglogical 2.3.3

### ISSUE THREAD

**Issue by boruiyan** [2ndQuadrant/pglogical#286]
I am trying to test pglogical 2.3.3 in Pg13 beta3 builder, but the regression test stuck at multiple_upstreams which takes 12+ hours and did not complete, I have tried ot serval times. And there is not output for multiple_upstreams in regression output. What could be the reason?

**Comment by boruiyan** [comment]
From postmaster :
```
[2020-10-07 18:09:11.414 UTC] [108090] [] LOG:  automatic analyze of table "regression.pglogical.depend" system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
[2020-10-07 18:09:27.607 UTC] [108064] [regression1] LOG:  process 108064 still waiting for ShareUpdateExclusiveLock on relation 18730 of database 16428 after 1000.106 ms
[2020-10-07 18:09:27.607 UTC] [108064] [regression1] DETAIL:  Process holding the lock: 108088. Wait queue: 108064.
[2020-10-07 18:09:35.261 UTC] [108092] [] LOG:  automatic analyze of table "postgres.pg_catalog.pg_sequence" system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
[2020-10-07 18:10:11.283 UTC] [108101] [] LOG:  automatic vacuum of table "regression.pg_catalog.pg_statistic": index scans: 1
        pages: 0 removed, 29 remain, 0 skipped due to pins, 0 skipped frozen
        tuples: 147 removed, 441 remain, 0 are dead but not yet removable, oldest xmin: 1440
        buffer usage: 105 hits, 0 misses, 0 dirtie
        avg read rate: 0.000 MB/s, avg write rate: 0.000 MB/s
        system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
        WAL usage: 54 records, 0 full page images, 4473 bytes
```
And 
```
regression1=# select oid,pg_database.datname from pg_database where oid='16428';
  oid  |   datname   
-------+-------------
16428 | regression1
(1 row)
regression1=# select oid, relname from pg_class where oid = '18730';
  oid  |  relname   
-------+------------
18730 | local_node
(1 row)
```
Stack trace for PID
```
[20:14:17][rdsdb][/build/dependencies/pglogical-REL2_3_3/regression_output/log]$ pstack 108088
#0  0x00007fd712b99f90 in epoll_pwait () from /lib64/libc.so.6
#1  0x00000000007762ca in WaitEventSetWaitBlock (nevents=1, occurred_events=0x7ffc108bf1e0, cur_timeout=-1, set=0x3138790) at latch.c:1294
#2  WaitEventSetWait (set=0x3138790, timeout=timeout@entry=-1, occurred_events=occurred_events@entry=0x7ffc108bf1e0, nevents=nevents@entry=1, wait_event_info=wait_event_info@entry=134217766) at latch.c:1246
#3  0x000000000077f92b in ConditionVariableTimedSleep (cv=0x7fd70ec14448, timeout=-1, wait_event_info=134217766) at condition_variable.c:180
#4  0x000000000074e56b in ReplicationSlotAcquireInternal (slot=slot@entry=0x0, name=name@entry=0x321d810 "pgl_postgres_test_provider1_test_subb8ed19d", behavior=behavior@entry=SAB_Block) at slot.c:450
#5  0x000000000074edbc in ReplicationSlotAcquire (name=name@entry=0x321d810 "pgl_postgres_test_provider1_test_subb8ed19d", behavior=behavior@entry=SAB_Block) at slot.c:368
#6  0x00000000007512f7 in pg_drop_replication_slot (fcinfo=<optimized out>) at slotfuncs.c:232
#7  0x000000000064f892 in ExecInterpExpr (state=0x321ca00, econtext=0x3210478, isnull=<optimized out>) at execExprInterp.c:699
#8  0x000000000067b177 in ExecEvalExprSwitchContext (isNull=0x7ffc108bf34f, econtext=0x3210478, state=0x321ca00) at ../../../src/include/executor/executor.h:313
#9  ExecProject (projInfo=0x321c9f8) at ../../../src/include/executor/executor.h:347
#10 ExecNestLoop (pstate=<optimized out>) at nodeNestloop.c:241
#11 0x0000000000652e3c in ExecProcNode (node=0x3210368) at ../../../src/include/executor/executor.h:245
#12 ExecutePlan (execute_once=<optimized out>, dest=0xb04fa0 <spi_printtupDR>, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_SELECT, use_parallel_mode=<optimized out>, planstate=0x3210368, estate=0x320fef8) at execMain.c:1646
#13 standard_ExecutorRun (queryDesc=0x7fd715256cb8, direction=<optimized out>, count=0, execute_once=<optimized out>) at execMain.c:364
#14 0x0000000000687b21 in _SPI_pquery (tcount=0, fire_triggers=true, queryDesc=<optimized out>) at spi.c:2511
#15 _SPI_execute_plan (plan=plan@entry=0x7ffc108bf4c0, paramLI=paramLI@entry=0x0, snapshot=snapshot@entry=0x0, crosscheck_snapshot=crosscheck_snapshot@entry=0x0, read_only=read_only@entry=false, fire_triggers=fire_triggers@entry=true, tcount=<optimized out>) at spi.c:2288
#16 0x0000000000687d7c in SPI_execute (src=src@entry=0x7fd70f346a10 "SELECT pg_catalog.pg_drop_replication_slot(slot_name)  FROM pg_catalog.pg_replication_slots WHERE (plugin = 'pglogical_output' OR plugin = 'pglogical')   AND database = current_database()   AND slot_n"..., read_only=read_only@entry=false, tcount=tcount@entry=0) at spi.c:514
#17 0x00007fd70f332bab in pglogical_drop_node (fcinfo=<optimized out>) at pglogical_functions.c:268
#18 0x000000000065b317 in ExecMakeTableFunctionResult (setexpr=0x312bd70, econtext=0x312bc40, argContext=<optimized out>, expectedDesc=0x312c960, randomAccess=false) at execSRF.c:234
#19 0x000000000066a925 in FunctionNext (node=0x312bb30) at nodeFunctionscan.c:94
#20 0x000000000065bb2a in ExecScanFetch (recheckMtd=0x66a680 <FunctionRecheck>, accessMtd=0x66a6a0 <FunctionNext>, node=0x312bb30) at execScan.c:133
#21 ExecScan (node=0x312bb30, accessMtd=0x66a6a0 <FunctionNext>, recheckMtd=0x66a680 <FunctionRecheck>) at execScan.c:182
#22 0x0000000000652e3c in ExecProcNode (node=0x312bb30) at ../../../src/include/executor/executor.h:245
#23 ExecutePlan (execute_once=<optimized out>, dest=0x31c7928, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_SELECT, use_parallel_mode=<optimized out>, planstate=0x312bb30, estate=0x312b908) at execMain.c:1646
#24 standard_ExecutorRun (queryDesc=0x3123908, direction=<optimized out>, count=0, execute_once=<optimized out>) at execMain.c:364
#25 0x0000000000798053 in PortalRunSelect (portal=portal@entry=0x316b538, forward=forward@entry=true, count=0, count@entry=9223372036854775807, dest=dest@entry=0x31c7928) at pquery.c:912
#26 0x0000000000799294 in PortalRun (portal=portal@entry=0x316b538, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x31c7928, altdest=altdest@entry=0x31c7928, qc=0x7ffc108bfa70) at pquery.c:756
#27 0x0000000000794f3d in exec_simple_query (query_string=0x30ff6b8 "SELECT * FROM pglogical.drop_node(node_name := 'test_provider1');") at postgres.c:1239
#28 0x00000000007971c9 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x3130c18, dbname=<optimized out>, username=<optimized out>) at postgres.c:4319
#29 0x00000000004c8cd9 in BackendRun (port=0x3126180, port=0x3126180) at postmaster.c:4599
#30 BackendStartup (port=0x3126180) at postmaster.c:4283
#31 ServerLoop () at postmaster.c:1802
#32 0x0000000000727b1c in PostmasterMain (argc=argc@entry=8, argv=argv@entry=0x30f7790) at postmaster.c:1475
#33 0x00000000004c9fb2 in main (argc=8, argv=0x30f7790) at main.c:210
```

**Comment by boruiyan** [comment]
It is not related with pglogical issue
